name: CD

on:
  push:
    branches: [main]

jobs:
  cd:
    uses: InventraTech/.github/.github/workflows/cd-python.yaml@main
    with:
      image-name: inventra-ai
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
